version: "3"
   
services:
  web:
    build: .
    restart: always
    container_name: FastZapTest
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis

    
  redis:
    image: "redis:alpine"
    command: redis-server
    ports: 
      - "6379:6379"
  
  celery:
    build:
      context: .
    entrypoint: celery
    command: -A FastZapTest worker --loglevel=info && -A FastZapTest beat -l info --pidfile= -f celery.log
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - redis